### ISSUE TITLE
convert_vcf_to_nexus does not write tab b/w species and sequence

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [mmatschiner/tutorials#2]
Dear Michael,
thank you for the great tutorial for using SNP data in SVD quartets. I have used the ruby script "convert_vcf_to_nexus.rb" you so kindly provided on my data set, which consists of SNPs generated from RADseq data using the IpyRAD assembly pipeline. When I tried to open the data with Paup*, I got an error message telling me the file was corrupted. When I inspected the nexus, I saw that there were no spaces between the sample identifier and the sequence. So it looked like this: (MeoahTTCNN...). Could you look into that? If necessary, I can provide my *.vcf file. Thank You.

Claudia

**Comment by mmatschiner** [comment]
Hi Claudia,
thanks for testing and the feedback! That part of the script was a bit sloppy, because it expected all IDs to be shorter than 10 charactes. I assume you didn't actually get "MeoahTTCNN..." but that instead of "Meoah" you had an ID with at least ten characters? I changed the script now that it should handle longer IDs. Could you check if it works now?

**Comment by ClaudiaPaetzold** [comment]
Hi Michael,
you were right, my sample IDs were longer than 10 digits. I just tested the new script, which works fine. Thank you for the quick response and the fix. And also: thank you for the tutorial for SVD quartets with SNP data. It helps me a great deal.
I will close this issue now.
Cheers
Claudia
